/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/ui/components/Alert.vue')['default']
    App: typeof import('./src/ui/App.vue')['default']
    BottomBar: typeof import('./src/ui/views/engine/BottomBar.vue')['default']
    Button: typeof import('./src/ui/components/Button.vue')['default']
    Card: typeof import('./src/ui/components/Card.vue')['default']
    Checkbox: typeof import('./src/ui/components/inputs/Checkbox.vue')['default']
    Chip: typeof import('./src/ui/components/misc/Chip.vue')['default']
    ContextBar: typeof import('./src/ui/views/engine/ContextBar.vue')['default']
    Divider: typeof import('./src/ui/components/misc/Divider.vue')['default']
    Documentation: typeof import('./src/ui/views/documentation/Documentation.vue')['default']
    DocumentationAlerts: typeof import('./src/ui/views/documentation/sections/DocumentationAlerts.vue')['default']
    DocumentationButtons: typeof import('./src/ui/views/documentation/sections/DocumentationButtons.vue')['default']
    DocumentationCards: typeof import('./src/ui/views/documentation/sections/DocumentationCards.vue')['default']
    DocumentationChips: typeof import('./src/ui/views/documentation/sections/DocumentationChips.vue')['default']
    DocumentationInputCheckboxes: typeof import('./src/ui/views/documentation/sections/inputs/DocumentationInputCheckboxes.vue')['default']
    DocumentationInputRadios: typeof import('./src/ui/views/documentation/sections/inputs/DocumentationInputRadios.vue')['default']
    DocumentationInputs: typeof import('./src/ui/views/documentation/sections/DocumentationInputs.vue')['default']
    DocumentationInputSwitches: typeof import('./src/ui/views/documentation/sections/inputs/DocumentationInputSwitches.vue')['default']
    DocumentationInputTextboxes: typeof import('./src/ui/views/documentation/sections/inputs/DocumentationInputTextboxes.vue')['default']
    DocumentationMenus: typeof import('./src/ui/views/documentation/sections/DocumentationMenus.vue')['default']
    DocumentationProgressBars: typeof import('./src/ui/views/documentation/sections/DocumentationProgressBars.vue')['default']
    DocumentationSection: typeof import('./src/ui/views/documentation/DocumentationSection.vue')['default']
    DocumentationTexts: typeof import('./src/ui/views/documentation/sections/DocumentationTexts.vue')['default']
    DocumentationTreeView: typeof import('./src/ui/views/documentation/sections/DocumentationTreeView.vue')['default']
    Engine: typeof import('./src/ui/views/engine/index.vue')['default']
    EntityComponent: typeof import('./src/ui/views/engine/ContextBar/EntityComponent.vue')['default']
    Home: typeof import('./src/ui/views/Home.vue')['default']
    InputNumber: typeof import('./src/ui/components/inputs/InputNumber.vue')['default']
    InputText: typeof import('./src/ui/components/inputs/InputText.vue')['default']
    InputVector3: typeof import('./src/ui/components/inputs/InputVector3.vue')['default']
    KeyboardKey: typeof import('./src/ui/components/KeyboardKey.vue')['default']
    Layout: typeof import('./src/ui/views/sandbox/Layout.vue')['default']
    LayoutBox: typeof import('./src/ui/views/sandbox/LayoutBox.vue')['default']
    LayoutResizer: typeof import('./src/ui/views/sandbox/LayoutResizer.vue')['default']
    Menu: typeof import('./src/ui/components/menus/Menu.vue')['default']
    MenuItem: typeof import('./src/ui/components/menus/MenuItem.vue')['default']
    MenuItemContent: typeof import('./src/ui/components/menus/MenuItemContent.vue')['default']
    ProgressBar: typeof import('./src/ui/components/ProgressBar.vue')['default']
    Radio: typeof import('./src/ui/components/inputs/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneView: typeof import('./src/ui/views/engine/SceneView.vue')['default']
    SideBar: typeof import('./src/ui/views/engine/SideBar.vue')['default']
    Switch: typeof import('./src/ui/components/inputs/Switch.vue')['default']
    Tab: typeof import('./src/ui/components/tabs/Tab.vue')['default']
    TabBar: typeof import('./src/ui/components/tabs/TabBar.vue')['default']
    Tabs: typeof import('./src/ui/components/tabs/Tabs.vue')['default']
    TabView: typeof import('./src/ui/components/tabs/TabView.vue')['default']
    TabViewContainer: typeof import('./src/ui/components/tabs/TabViewContainer.vue')['default']
    Textbox: typeof import('./src/ui/components/inputs/Textbox.vue')['default']
    Toolbar: typeof import('./src/ui/components/Toolbar.vue')['default']
    TransformComponent: typeof import('./src/ui/views/engine/ContextBar/TransformComponent.vue')['default']
    TreeView: typeof import('./src/ui/components/TreeView.vue')['default']
  }
}
